import react from "@vitejs/plugin-react";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { defineConfig, type Alias, type PluginOption } from "vite";

const hostDir = dirname(fileURLToPath(import.meta.url));

/**
 * Dev only: KV_VAULT_PKG=<path to a bai-knowledge-note checkout> (`bun run dev:vault`) serves the
 * vault package from its source with hot reload — the way Connect's dev server serves a local
 * package — instead of the published build in node_modules. Never set for builds or CI.
 */
const vaultPkg = process.env.KV_VAULT_PKG ? resolve(process.env.KV_VAULT_PKG) : undefined;
if (vaultPkg && !existsSync(join(vaultPkg, "index.ts"))) throw new Error(`KV_VAULT_PKG=${vaultPkg} is not a vault package checkout (no index.ts).`);

// One copy each: a second reactor-browser would not see the same window.ph brands.
const SHARED = ["react", "react-dom", "@powerhousedao/reactor-browser", "document-model"];

/** The vault source's stylesheet, compiled by Tailwind with the vault's own sources scanned. */
function vaultStylesheet(pkg: string): string {
  const dir = join(hostDir, ".vault-dev");
  mkdirSync(dir, { recursive: true });
  const file = join(dir, "vault.css");
  writeFileSync(
    file,
    [
      "/* Generated by host/vite.config.ts for `bun run dev:vault`: the vault's source stylesheet, with its sources scanned. */",
      `@import "${join(pkg, "style.css")}";`,
      `@source "${join(pkg, "editors")}";`,
      `@source "${join(pkg, "document-models")}";`,
      "",
    ].join("\n"),
  );
  return file;
}

async function vaultSource(pkg: string): Promise<{ plugins: PluginOption[]; alias: Alias[] }> {
  // Tailwind's Vite plugin comes from the vault checkout: the desktop app itself does not use Tailwind.
  const tailwind = (await import(pathToFileURL(join(pkg, "node_modules/@tailwindcss/vite/dist/index.mjs")).href)) as { default: () => PluginOption };
  return {
    plugins: [tailwind.default()],
    alias: [
      { find: /^@powerhousedao\/knowledge-note\/style\.css$/, replacement: vaultStylesheet(pkg) },
      { find: /^@powerhousedao\/knowledge-note$/, replacement: join(pkg, "index.ts") },
    ],
  };
}

export default defineConfig(async () => {
  const source = vaultPkg ? await vaultSource(vaultPkg) : undefined;
  return {
    plugins: [react(), ...(source?.plugins ?? [])],
    server: {
      port: 4200,
      strictPort: true,
      host: "127.0.0.1",
      ...(vaultPkg
        ? {
            fs: { allow: [resolve(hostDir, ".."), vaultPkg] },
            watch: { ignored: ["**/.ph/**", "**/backup-documents/**", "**/dist/**", "**/scripts/drive-sync/data/**", "**/.superpowers/**"] },
          }
        : {}),
    },
    resolve: {
      dedupe: vaultPkg ? [...SHARED, "@powerhousedao/design-system"] : SHARED,
      ...(source ? { alias: source.alias, tsconfigPaths: true } : {}),
    },
    // Imported lazily by sidecar.ts under Tauri; pre-bundling them avoids a mid-session re-optimisation (stale chunk names on first load).
    optimizeDeps: { include: ["@tauri-apps/api/core", "@tauri-apps/api/event"] },
    // The dev loop gives each run its own cache (scripts/dev.mjs), so nothing else rewrites it mid-session.
    ...(process.env.KV_VITE_CACHE ? { cacheDir: process.env.KV_VITE_CACHE } : {}),
  };
});
